name: ci

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test code
        run: go test -v .